#
# Makefile to build the UPC Language Specification.
#
# Run with BUILD_HTNL asserted to also build the
# HTML formatted specification:
#     make BUILD_HTML=1
#
NAME = upc-lib-castability-spec

COMMON = ../../../common

TEX_INC_SRCS = \
	$(COMMON)/upc-spec-preamble.tex \
	$(COMMON)/upc-specification-issues.tex \
	upc-lib-castability-spec.tex \
	upc-lib-castability-spec-draft.tex \
	upc-lib-castability.tex

include $(COMMON)/Makefile.in
