#
# Makefile to build the UPC Language Specification.
#
# Run with BUILD_HTNL asserted to also build the
# HTML formatted specification:
#     make BUILD_HTML=1
#
NAME = upc-lib-required-spec

COMMON = ../../common

TEXSRCS =

TEX_INC_SRCS = \
	$(COMMON)/upc-spec-prolog.tex \
	upc-lib-collectives.tex

include $(COMMON)/Makefile.in
