#
# Makefile to build the UPC Language Specification.
#
# Run with BUILD_HTML asserted to also build the
# HTML formatted specification:
#     make BUILD_HTML=1
#
NAME = upc-lib-template-spec

COMMON = ../../../common

TEX_INC_SRCS = \
	$(COMMON)/upc-spec-preamble.tex \
	$(COMMON)/upc-specification-issues.tex \
	upc-lib-template-spec.tex \
	upc-lib-template.tex

include $(COMMON)/Makefile.in
