#
# Makefile to build the UPC Language Specification.
#
# Run with BUILD_HTNL asserted to also build the
# HTML formatted specification:
#     make BUILD_HTML=1
#
NAME = upc-lib-nb-mem-ops-spec

COMMON = ../../../common

TEX_INC_SRCS = \
	$(COMMON)/upc-spec-preamble.tex \
	upc-lib-nb-mem-ops.tex

include $(COMMON)/Makefile.in
